### ISSUE TITLE
I am very curious about the project will continue to maintain and update?

### ISSUE THREAD

**Issue by Gary-code** [xinetzone/d2py#1]
I am very curious about the project will continue to maintain and update?

**Comment by xinetzone** [comment]
This project will be constantly updated with new, fun, Python-related content.

**Comment by Gary-code** [comment]
I think this project is inpired by [d2l](https://github.com/d2l-ai/d2l-zh). I am quite interested to be a contributor of this attractive project. Welcome to share some ideas about this project.

**Comment by xinetzone** [comment]
My initial plan is to implement mathematically relevant concepts using Python type annotations.

**Comment by Gary-code** [comment]
> 

Thanks to you answer. However, I'm still uncertain about some details of these project, such as the targeted people of these project, some basic roadmap and the goal of the project. If the targeted people are Zero-based Python enthusiast or related professional student. I'm very interested to help you improve the project if I'm free, considering that I'm still an Undergraduate. Welcome to contact me at any time.

**Comment by xinetzone** [comment]
We can communicate directly in Chinese.

**Comment by xinetzone** [comment]
Target audience:

1. Python enthusiast;
2. Mathematics major or scholar (physics is also acceptable, I am also interested in physics);
3. People who want to implement interesting projects in Python;

**Comment by xinetzone** [comment]
当下的主要目标是：

1. 使用 Python 实现数学分析、高等代数、概率统计、泛函分析的相关数学概念；
2. 编写一些自动化办公的软件；
3. 编写友好的任务流程化工具；
4. 编写文档（包含 PDF、LaTex、HTML、Word）自动化生成工具。

**Comment by xinetzone** [comment]
当前正在组织本项目的一个子项目：[pytorch-book](https://xinetzone.github.io/pytorch-book/index.html).

下面正在计划把本项目的构建和组织方式，变更为 [pytorch-book](https://xinetzone.github.io/pytorch-book/index.html) 的风格。自定义一种新的 Sphinx 主题为 d2py 服务。并且，把 Sphinx 的细节隐藏，便于后期维护和开发。

**Comment by xinetzone** [comment]
当前也需要定制详细的[贡献者指南](https://github.com/xinetzone/d2py/blob/main/docs/CONTRIBUTING.md) 、用户使用手册、开发者指南。

**Comment by Gary-code** [comment]
好的非常感谢你的耐心解答

**Comment by xinetzone** [comment]
@Gary-code 可以参与到 #2 ，共同开发这个项目。
